import os

MAX_ERROR_RUN = 3
MAX_RUN_PER_QUESTION =10
MAX_QUESTION_TO_KEEP = 3
MAX_QUESTION_WITH_DETAIL_HIST = 1

OPENAI_EMB_DEPLOYMENT = os.getenv("OPENAI_EMB_DEPLOYMENT","text-embedding-ada-002")
OPENAI_GPT4_DEPLOYMENT =os.getenv("OPENAI_GPT4_DEPLOYMENT","gpt-4o")
OPENAI_GPT35_DEPLOYMENT =os.getenv("OPENAI_GPT35_DEPLOYMENT","gpt-4o")
SQLITE_DB_PATH= os.environ.get("SQLITE_DB_PATH","data/northwind.db")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY","")

